### ISSUE TITLE
Broken in Firefox - "can't read and change data on this site"

### ISSUE THREAD

**Issue by piousminion** [veteran29/steam-url-open-extension#16]
OS: Windows 10 Enterprise LTSC (64-bit)  -- Don't judge.  :stuck_out_tongue_winking_eye:
Browser: Firefox 116.0.2 (64-bit)

Issue:   Doesn't work, at all.
Steps:  Go to any Steam URL
Result: The extension icon and text in Firefox's extension drawer is greyed out with the text  reading "can't read and change data on this site"

I thought it was some quirk of Librewolf(firefox fork) I was using, but a FRESH Firefox install has the same result.
If there is any information you might need to help resolve this, do not hesitate to ask. :)

Screenshot:
![firefox_qPI0DxxTiK](https://github.com/veteran29/steam-url-open-extension/assets/315001/5e335511-d98e-42da-a58f-ccda25ddab28)

**Comment by UltraBlackLinux** [comment]
that's because you use the small steam button in the url bar

**Comment by RunningDroid** [comment]
That's because it doesn't access data on the site:
![2023-11-23T00:53:07,517314487-05:00](https://github.com/veteran29/steam-url-open-extension/assets/486393/c2102209-80f9-4d84-b0cb-57c67fd2da45)
It gets the page's URL through [Access Browser Tabs](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions#w_access-browser-tabs), and generates the steam URL from that:
https://github.com/veteran29/steam-url-open-extension/blob/1effd0cc632ba6baa1be07e61a3c0dc0415a052e/app/scripts/background.js#L9

If the button in the URL bar isn't working, then that's probably issue #15
